version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - 3306:3306
    restart: always
  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Mot de passe root
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Nom de la base de données
      MYSQL_USER: ${MYSQL_USER} # Nom d'utilisateur
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Mot de passe de l'utilisateur
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET} # Clé secrète pour JWT

  backend:
    depends_on:
      - db
    build: ./back
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET} # Clé secrète pour JWT
    ports:
      - 8080:8080

  frontend:
    depends_on:
      - db
    build: ./front
    ports:
      - 4200:4200
