version: "3.3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdd_mdd
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mdd-network

  backend:
    build: ./back
    container_name: springboot-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bdd_mdd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    networks:
      - mdd-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./front
    container_name: angular-container
    ports:
      - "4200:4200"
    networks:
      - mdd-network
    depends_on:
      - backend

volumes:
  mysql-data:

networks:
  mdd-network:
    driver: bridge
